src/test/java/com/cronutils/mapper/CronMapperIntegrationTest.java
=> Added Days of Week  Unix2Quartz mapper test

src/main/java/com/cronutils/model/time/ExecutionTime.java, src/test/java/com/cronutils/model/time/ExecutionTimeIntegrationTest.java
=> Issue #19: Fix nextExecution/lastExecution datetime shifting

src/main/java/com/cronutils/parser/field/FieldParser.java, src/test/java/com/cronutils/parser/CronParserTest.java
=> fix ArrayIndexOutOfBoundsException when parsing incomplete steps expr.

src/main/java/com/cronutils/model/time/generator/OnDayOfMonthValueGenerator.java, src/test/java/com/cronutils/model/time/ExecutionTimeQuartzIntegrationTest.java
Adding Test and Code Fix for failing cron-expression evaluation with 'W' flag for quartz expression.
0 0 12 1W * ? *
=> Danoom issue74 quartzron w flag

src/test/java/com/cronutils/model/time/generator/ExecutionTimeUnixIntegrationTest.java
add failing test as requested in issue #79
=> add failing test for issue #79

src/main/java/com/cronutils/model/time/generator/BetweenFieldValueGenerator.java, src/test/java/com/cronutils/model/time/ExecutionTimeQuartzIntegrationTest.java
Taking the from and to values into account when getting the next and previous values respectively in the BetweenFieldValueGenerator.
=> Issue83 Combined Ranges

src/test/java/com/cronutils/model/time/generator/ExecutionTimeUnixIntegrationTest.java
Hi. I've prepared a failing unit test for issue #92, based on the code sample provided by the reporter. Would you be interested in merging it?
=> Failing unit test for issue #92

src/test/java/com/cronutils/model/time/ExecutionTimeQuartzIntegrationTest.java, src/test/java/com/cronutils/parser/CronParserQuartzIntegrationTest.java
Add the Scala tests by @francisdb to cron-utils (#91).
=> Add tests for #91

pom.xml, src/main/java/com/cronutils/StringValidations.java, src/main/java/com/cronutils/builder/CronBuilder.java
The code quality/readability is now enhanced a little bit. I would like
to use this tool therefore I would like to contribute to make it better.
Are you interested in a collaboration?
=> Java 7 and code readability

README.md
Added Java syntax highlighting to code snippets inside README.md
=> Added java syntax highlighting to README.md

src/test/java/com/cronutils/utils/descriptor/CronDescriptorQuartzIntegrationTest.java
Added a failing unit test for issue #103 based on the code snippet provided by the issue's reporter.
=> Issue #103

src/main/java/com/cronutils/model/field/expression/visitor/ValidationFieldExpressionVisitor.java, src/test/java/com/cronutils/model/field/expression/visitor/ValidationFieldExpressionVisitorTest.java
Fix validation of "and" fieldexpression list and add unit tests for the visitor
=> Fix validation of "and" fieldexpression list

src/test/java/com/cronutils/Issue143Test.java
Hi, if you need more information, please let me know.
=> Add Test Case for Issue#143

README.md, src/main/java/com/cronutils/Main.java
Please accept this PR that makes possible to use cron-utils without creating a whole project to validate a cron expression.
Cheers,
Bertrand
=> Implementation of a standalone mode

pom.xml
Build with mvn assembly:assembly -DdescriptorId=jar-with-dependencies
=> Support for uber jars

README.md, src/main/java/com/cronutils/cli/CronUtilsCLI.java
use -v or (better) , --validate
=> Validation option now without argument

.gitignore, src/main/java/com/cronutils/model/field/constraint/FieldConstraints.java, src/main/java/com/cronutils/model/field/expression/visitor/ValidationFieldExpressionVisitor.java, src/test/java/com/cronutils/parser/CronParserTest.java
=> fixed issue #148

src/androidTest/java/com/cronutils/Issue55UnexpectedExecutionTimes.java, src/androidTest/java/com/cronutils/model/definition/CronDefinitionBuilderTest.java, src/androidTest/java/com/cronutils/model/time/ExecutionTimeCustomDefinitionIntegrationTest.java, src/main/java/com/cronutils/model/definition/CronDefinition.java, src/main/java/com/cronutils/model/definition/CronDefinitionBuilder.java, src/main/java/com/cronutils/model/field/CronFieldName.java, src/main/java/com/cronutils/model/field/definition/DayOfWeekFieldDefinition.java, src/main/java/com/cronutils/model/field/definition/FieldDayOfWeekDefinitionBuilder.java, src/main/java/com/cronutils/model/field/definition/FieldDefinition.java, src/main/java/com/cronutils/model/field/definition/FieldDefinitionBuilder.java, src/main/java/com/cronutils/model/time/ExecutionTime.java, src/main/java/com/cronutils/parser/CronParser.java, src/main/java/com/cronutils/parser/CronParserField.java, src/test/java/com/cronutils/Issue55UnexpectedExecutionTimes.java, src/test/java/com/cronutils/model/definition/CronDefinitionBuilderTest.java, src/test/java/com/cronutils/model/definition/CronDefinitionTest.java, src/test/java/com/cronutils/model/time/ExecutionTimeCustomDefinitionIntegrationTest.java, src/test/java/com/cronutils/model/time/ExecutionTimeQuartzIntegrationTest.java
added cleanups, i.e. removed unused imports
=> Revise improved handling of optional cron expression fields

src/main/java/com/cronutils/model/time/ExecutionTime.java, src/test/java/com/cronutils/model/time/ExecutionTimeQuartzWithDayOfYearExtensionIntegrationTest.java
added unit test for issue #190
fixed issue #190
@jmrozanec Thanks for your patience and any inconvenience!
=> added unit test and fix for issue #190

src/main/java/com/cronutils/model/definition/CronDefinitionBuilder.java, src/main/java/com/cronutils/parser/FieldParser.java, src/test/java/com/cronutils/model/definition/TestCronDefinitionsFactory.java, src/test/java/com/cronutils/parser/CronParserQuartzIntegrationTest.java
- added tests
- added Javadoc
- revised Quartz CronDefinition
- reject special character # (hash) if not allowed
=> Revise quartz cron definition to fully comply with Quartz specification

.gitignore, src/main/java/com/cronutils/model/field/constraint/FieldConstraintsBuilder.java, src/main/java/com/cronutils/model/field/definition/FieldDayOfWeekDefinitionBuilder.java, src/test/java/com/cronutils/parser/CronParserCron4JIntegrationTest.java
added unit test for issue 202 as provided by pangyikhei
=> fixed issue 202

src/androidTest/java/com/cronutils/model/time/ExecutionTimeQuartzIntegrationTest.java, src/main/java/com/cronutils/model/time/generator/BetweenFieldValueGenerator.java, src/main/java/com/cronutils/model/time/generator/EveryFieldValueGenerator.java, src/test/java/com/cronutils/model/time/ExecutionTimeQuartzIntegrationTest.java
extended test on issue 144 (i.e.
testPeriodicIncrementalHoursIgnorePeriodBounds) in order to test
#lastExecution too.
=> fixed issue 144

src/test/java/com/cronutils/Issue215Test.java
=> test for issue https://github.com/jmrozanec/cron-utils/issues/215

src/main/java/com/cronutils/model/time/generator/AndFieldValueGenerator.java
This is preventing running under JDK7.
=> Remove unused java.util.stream.Collectors import

pom.xml
The are a few other possible ways to fix #211 
Like removing this dependency and only relying on the transitive dep
=> Fix issue 211

src/main/java/com/cronutils/descriptor/TimeDescriptionStrategy.java, src/test/java/com/cronutils/utils/descriptor/CronDescriptorQuartzIntegrationTest.java
Updated the parsing logic so that it inspects the period for the hour component
=> Fix for issue #43

src/main/java/com/cronutils/descriptor/TimeDescriptionStrategy.java, src/test/java/com/cronutils/utils/descriptor/Issue227Test.java
Closing issue 227 - one of multiple available approches.
=> Close Issue #227

src/main/java/com/cronutils/model/time/ExecutionTime.java, src/test/java/com/cronutils/Issue218Test.java
Change generator arguments for proper one.
=> Close Issue #218

src/main/java/com/cronutils/parser/FieldParser.java, src/test/java/com/cronutils/Issue223Test.java
Change FieldParser - better expression recognition,
=> Close Issue #223

src/test/java/com/cronutils/utils/descriptor/CronDescriptorQuartzIntegrationTest.java
=> Issue #105

src/main/java/com/cronutils/descriptor/DescriptionStrategy.java, src/main/java/com/cronutils/descriptor/DescriptionStrategyFactory.java, src/main/java/com/cronutils/descriptor/TimeDescriptionStrategy.java, src/main/java/com/cronutils/mapper/CronMapper.java, src/main/java/com/cronutils/mapper/WeekDay.java, src/main/java/com/cronutils/model/definition/CronDefinitionBuilder.java, src/main/java/com/cronutils/model/field/CronField.java, src/main/java/com/cronutils/model/time/generator/AndFieldValueGenerator.java, src/main/java/com/cronutils/parser/CronParserField.java, src/test/java/com/cronutils/model/definition/CronDefinitionTest.java, src/test/java/com/cronutils/model/field/expression/visitor/ValueMappingFieldExpressionVisitorTest.java
Changes to match Java 7 language level.
- replaces lambda expressions with anonymous classes
- uses Collections.sort instead of List.sort (only available in Java 8+)
- Lists.newArrayList and Sets.newHashSet usages replaced with appropriate constructor methods where not permitted by Java 7
=> Issue #221

src/main/java/com/cronutils/model/time/ExecutionTime.java, src/test/java/com/cronutils/model/time/ExecutionTimeCustomDefinitionIntegrationTest.java
https://github.com/jmrozanec/cron-utils/issues/246
Add in a test for day of month / day of week when one is specified exactly and one is set to always; merge the two generateDayCandidates methods together, generating the ALWAYS candidates after the question marks
=> Fix Issue 246

src/main/java/com/cronutils/model/time/ExecutionTime.java, src/test/java/com/cronutils/model/time/ExecutionTimeQuartzIntegrationTest.java, src/test/java/com/cronutils/model/time/ExecutionTimeQuartzWithDayOfYearExtensionIntegrationTest.java
see TestCase ExecutionTimeQuartzWithDayOfYearExtensionIntegrationTest#testCustomQuarterlySchedule
=> fixed ExecutionTimeQuartzWithDayOfYearExtensionIntegrationTest#testCustomQuarterlySchedule

src/main/java/com/cronutils/descriptor/NominalDescriptionStrategy.java, src/main/java/com/cronutils/descriptor/TimeDescriptionStrategy.java, src/main/java/com/cronutils/mapper/CronMapper.java, src/main/java/com/cronutils/model/field/expression/Always.java, src/main/java/com/cronutils/model/field/expression/Every.java, src/main/java/com/cronutils/model/field/expression/FieldExpressionFactory.java, src/main/java/com/cronutils/model/field/expression/QuestionMark.java, src/main/java/com/cronutils/model/field/expression/visitor/ValueMappingFieldExpressionVisitor.java, src/main/java/com/cronutils/model/time/ExecutionTimeBuilder.java, src/main/java/com/cronutils/parser/FieldParser.java
=> Replace use of deprecated constructor for Always and QuestionMark

.checkstyle
Added a checkstyle configuration file that can be used by the checkstyle
plugin for eclipse. http://eclipse-cs.sourceforge.net/#!/
=> Added a checkstyle configuration for eclipse.

.travis.yml
Adding check for pull request, doing `mvn verify` instead of `mvn deploy`
=> Add Pull Request specific built script

src/test/java/com/cronutils/model/time/ExecutionTimeCustomDefinitionIntegrationTest.java, src/test/java/com/cronutils/model/time/generator/ExecutionTimeUnixIntegrationTest.java
See: https://sonarcloud.io/project/issues?id=cron-utils&open=AWAUYNwdokCP5-bHbgwt&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL
=> #285 fix sonarqube issues

src/test/java/com/cronutils/utils/descriptor/TestDescriptor.java
All added tests are currently ignored. (so that the build wont break)
=> #3 Added Description tests that need to fixed.

src/main/java/com/cronutils/utils/DateUtils.java
This fixes the failing tests on master and PRs
=> Use proper method in DateUtils

src/main/java/com/cronutils/model/time/SingleExecutionTime.java
=> [WIP] Fix #328: Add truncation to some `getPreviousPotentialXXX` methods

src/main/java/com/cronutils/model/time/SingleExecutionTime.java, src/test/java/com/cronutils/Issue332Test.java
Fixes #332 
I would greatly appreciate if we could get a new 7.x.x release with these changes after they have merged.
=> Fix infinite loop with midnight DST start

src/main/resources/CronUtilsI18N_fr.properties
=> Correct typo French second to seconde

src/test/java/com/cronutils/Issue338Test.java
=> Correct French translation

src/test/java/com/cronutils/Issue340Test.java
Added a test which demonstrates #340
=> Issue 340: Added test for issue 340

src/main/java/com/cronutils/model/time/SingleExecutionTime.java
See https://github.com/jmrozanec/cron-utils/issues/319#issuecomment-427771999
=> Limit iterations

src/main/java/com/cronutils/model/time/SingleExecutionTime.java
Follow up to #351
To hopefully avoid issues similar to #319 when computing next potential times.
=> Simplify next potential time calculation

src/main/java/com/cronutils/model/time/generator/EveryDayOfWeekValueGenerator.java, src/main/java/com/cronutils/model/time/generator/EveryFieldValueGenerator.java, src/main/java/com/cronutils/model/time/generator/FieldValueGeneratorFactory.java, src/test/java/com/cronutils/model/time/generator/EveryDayOfWeekValueGeneratorTest.java, src/test/java/com/cronutils/model/time/generator/ExecutionTimeUnixIntegrationTest.java
Fixes the day of week handling for the "every" expression.
The testCorrectNextExecutionDoW test in ExecutionTimeUnixIntegrationTest was also expecting the wrong next execution time value so I fixed that test.
=> #336 - Fix Every Day Of Week handling

src/main/java/com/cronutils/model/definition/CronDefinitionBuilder.java
=> Remove unsupported characters from spring definition.

src/main/java/com/cronutils/parser/FieldParser.java, src/test/java/com/cronutils/parser/CronParserTest.java
=> Proper error when expression contains an incomplete range.

src/main/java/com/cronutils/parser/CronParserField.java, src/test/java/com/cronutils/parser/CronParserFieldTest.java
=> Correctly parse last DoW values

src/test/java/com/cronutils/Issue388Test.java
Wrong execution time with `dow` and `dom` with spring cron parser
=> Add test for issue #388 -

src/test/java/com/cronutils/Issue363Test.java
Fixed the test from #363 and added a test for what seems to be the intended expression from the author.
=> Fixed test for #363. Added test for intended expression.

pom.xml, src/main/java/com/cronutils/converter/BaseCronTransformer.java, src/main/java/com/cronutils/converter/CalendarToCronTransformer.java, src/main/java/com/cronutils/converter/CronConverter.java, src/main/java/com/cronutils/converter/CronToCalendarTransformer.java, src/test/java/com/cronutils/converter/CronConverterTest.java
This add the feature mentioned in Issue: #243
=> Changes to convert cron from one timezone to another.

src/main/java/com/cronutils/model/time/generator/EveryFieldValueGenerator.java, src/test/java/com/cronutils/model/time/ExecutionTimeCron4jIntegrationTest.java
=> Fix for incorrect time sequence generation for expression "0 10/4 * * *"

src/main/java/com/cronutils/model/definition/CronConstraintsFactory.java
I'm not sure if I'm doing the right thing here. But the NPE is indeed possible.
=> Fix NPE when checking cron constraints

src/test/java/Issue421Test.java
Hi,
this is a test for the issue #421.
Please review (it could be an expected behaviour?) and let me know what you think.
Best regards
P.S. Sorry for souts, couldn't get logger working 🤷‍♂️
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
=> Issue #421 test

src/main/java/com/cronutils/descriptor/CronDescriptor.java
=> allow resourceBundle in CronDescriptor  constructor

src/main/java/com/cronutils/descriptor/DescriptionStrategy.java, src/test/java/com/cronutils/Issue440Test.java, src/test/java/com/cronutils/converter/CronConverterTest.java
I've tried this way to fix issue #440 , let me know if is it okay
I've found also something strange: 
- in CronConverterTest.java method testCronConverterBuilder produced an error after checkout, I've put a comment so code compile
=> PR for issue #440

src/main/java/com/cronutils/descriptor/TimeDescriptionStrategy.java, src/main/resources/CronUtilsI18N_en.properties, src/test/java/com/cronutils/Issue439Test.java, src/test/java/com/cronutils/converter/CronConverterTest.java
My proposed description for case is "every second at minute 00 of every hour"
=> PR for issue #439

src/main/java/com/cronutils/model/time/SingleExecutionTime.java, src/test/java/com/cronutils/model/time/ExecutionTimeQuartzIntegrationTest.java
Fixed #428 and added the test case for valid range
﻿
=> #428 Pass valid range constraints from cron definition to execution time

src/test/java/com/cronutils/Issue446Test.java
Additional failing case for issue #446
=> Additional failing test for issue #446

src/test/java/com/cronutils/Issue462Test.java
JUnit test for
https://github.com/jmrozanec/cron-utils/issues/462
=> PR for testing of issue 462

src/test/java/com/cronutils/Issue477Test.java
=> Add test for issue #477

src/test/java/com/cronutils/Issue480Test.java
=> Issue 480 test

src/main/java/com/cronutils/parser/CronParser.java, src/test/java/com/cronutils/Issue418Test.java, src/test/java/com/cronutils/parser/CronParserQuartzIntegrationTest.java, src/test/java/com/cronutils/validation/CronValidatorTest.java
Make tests a bit more resilient to exception message changes.
fixes #461
=> Resolve RCE vulnerability.

src/test/java/com/cronutils/Issue499Test.java
Requested in https://github.com/jmrozanec/cron-utils/issues/499
=> Test for Issue #499

pom.xml, pom.xml.jdk16
The tests pass and snyk no longer complains about the vulnerability.
=> Fix for #517 Input Validation Vulnerability in Dependency

pom.xml
Javassist doesn't seem to be used
=> Remove Javassist

src/main/java/com/cronutils/parser/CronParser.java, src/test/java/com/cronutils/parser/CronParserNicknameTest.java
=> Fix IllegalArgumentException when trying to parse `@monthly` nickname

pom.xml, src/main/java/com/cronutils/model/definition/CronConstraint.java, src/main/java/com/cronutils/model/definition/CronDefinition.java, src/test/java/com/cronutils/model/definition/CronDefinitionTest.java
implement equals and hash code for CronDefinition with corresponding tests
resolve #507
=> implement equals and hash code

src/test/java/com/cronutils/Issue528Test.java
=> Add unit test for #528

src/test/java/com/cronutils/Issue539Test.java
See #539 for details of the issue.
=> [BUG] Add failing test for issue #539
