jmrozanec/cron-utils

- src/main/java/com/cronutils/model/time/TimeNode.java
- src/test/java/com/cronutils/model/time/TimeNodeTest.java
- src/test/java/com/cronutils/model/time/generator/ExecutionTimeUnixIntegrationTest.java
Fix for TimeNode.getNearestBackwardValue to correctly handle situations where the value we are looking for is not in the current list and there are no smaller values in the list.
This fixes issue #50 where cron definitions containing a day of the week would not be handled correctly when getting the last execution when the last execution was in the previous month.
> Fix for issue #50

- src/main/java/com/cronutils/model/time/generator/AndDayOfWeekValueGenerator.java
- src/main/java/com/cronutils/model/time/generator/FieldValueGeneratorFactory.java
- src/test/java/com/cronutils/model/time/generator/ExecutionTimeUnixIntegrationTest.java
- src/test/java/com/cronutils/model/time/generator/FieldValueGeneratorFactoryTest.java
Fix for issue #52 - Specifying multiple comma separated days of the week in a cron expression was not handled as a special case, so e.g. 1,2 (Monday and Tuesday) was being handled as 1st/2nd of month.
> Fix dayofweek and expression

- src/main/java/com/cronutils/model/field/constraint/FieldConstraints.java
- src/main/java/com/cronutils/model/field/expression/FieldExpression.java
- src/main/java/com/cronutils/model/time/generator/EveryFieldValueGenerator.java
- src/test/java/com/cronutils/model/time/generator/ExecutionTimeUnixIntegrationTest.java
Currently the way to calculate "next value" in "Every" situation is incorrect to me.
For "DoM", the valid range starts from 1 instead of 0, and 1 is always selected for cases like */(a random number). So I purpose a new way to generateNextValue which is "start value + period", and change isMatch to (value - start value) % period.
> Fix incorrect next execution time for "day of month" in "Every" situation

- src/main/java/com/cronutils/mapper/WeekDay.java
- src/main/java/com/cronutils/model/field/constraint/FieldConstraintsBuilder.java
- src/main/java/com/cronutils/model/field/definition/FieldDayOfWeekDefinitionBuilder.java
- src/test/java/com/cronutils/model/time/ExecutionTimeQuartzIntegrationTest.java
- src/test/java/com/cronutils/validator/CronValidatorQuartzIntegrationTest.java
Sorry I'm late with response to the opened issue. The original problem was that when parsing MON,TUE,.. day names in quartz cron, they were incorrectly mapped to their integer representation (statically created stringMapping). 
In this branch, if you select withMondayDoWValue(n) during building your cron definition, the string mapping is shifted into correct position. (method is public so it should work generically even with month definitions)
One problem that arose is that from now on if you have cron expression like 0 0 12 ? * SAT-SUN it fails to validate because it's mapped to 7-1 and validators won't allow 7 being larger than 1. (see CronValidatorQuartzIntegrationTest)
Even though it's valid quartz expression (I was using http://www.cronmaker.com/ as reference)
If you give me some …
> Issue81 incorrect date generation

- src/main/java/com/cronutils/descriptor/DescriptionStrategyFactory.java
- src/main/java/com/cronutils/mapper/ConstantsMapper.java
- src/main/java/com/cronutils/model/field/expression/FieldExpressionFactory.java
This pull request is focused on resolving occurrences of Sonar rule
squid:S1118 - "Utility classes should not have public constructors".
You can find more information about the issue here:
https://sonar.spring.io/coding_rules#rule_key=squid:S1118
Please let me know if you have any questions.
Artyom Melnikov
> Fixing squid:S1118 - Utility classes should not have public constructors

- src/main/java/com/cronutils/model/time/generator/FieldValueGeneratorFactory.java
- src/test/java/com/cronutils/model/time/generator/FieldValueGeneratorFactoryTest.java
`FieldValueGeneratorFactory` has a `factory` field holding singleton instance of this class. But since this class has no state and only static methods, this instance, along with its getter method, is unnecessary. I'd like to suggest removing it entirely.
> Minor FieldValueGeneratorFactory refactoring

- src/main/java/com/cronutils/model/field/expression/visitor/ValidationFieldExpressionVisitor.java
- src/test/java/com/cronutils/model/field/expression/visitor/ValidationFieldExpressionVisitorTest.java
Fix validation of "and" sub fieldexpressions and add unit tests for ValidationFieldExpressionVisitor, based on tag 4.1.1
> Fix validation of "and" sub fieldexpressions

- src/test/java/com/cronutils/model/time/ExecutionTimeQuartzIntegrationTest.java
cron like "0 0 0 31 * ?" will cause executionTime.lastExecution(zonedDateTime) throw an exception when  zonedDateTime.getDayOfMonth() less than 31, just like current month.
thanks.
> add a test case for month end 

- src/main/java/com/cronutils/descriptor/CronDescriptor.java
- src/main/java/com/cronutils/descriptor/DescriptionStrategyFactory.java
- src/main/java/com/cronutils/model/definition/CronDefinition.java
The Quartz definition uses a Monday value of 2 whilst the java.util.DayOfWeek class used starts with a Monday of 1 which causes the description to be incorrect, i.e. Monday becomes Tuesday and so forth. The fix is to use the field definition from the Cron expession to map back to the DayOfWeek enumeration to rectivfy the issue.
```
public static DescriptionStrategy daysOfWeekInstance(final ResourceBundle bundle, final FieldExpression expression, final FieldDefinition definition) {
final Function<Integer, String> nominal = integer -> {
int diff = definition instanceof DayOfWeekFieldDefinition ? DayOfWeek.MONDAY.getValue() - ((DayOfWeekFieldDefinition) definition).getMondayDoWValue().getMondayDoWValue() : 0;
return DayOfWeek.of(integer + diff < 1 ? 7 : integer + …
```
> Issues #114 Use the CronDefintion to map to the DayOfWeek description

- src/test/java/com/cronutils/parser/CronParserQuartzIntegrationTest.java
Currently throws a "java.lang.RuntimeException: Non integer values at intervals are not fully supported yet."
> issue #151: Added a broken test for L-x day ranges in quartz. 

- src/main/java/com/cronutils/mapper/WeekDay.java
- src/main/java/com/cronutils/model/Cron.java
- src/main/java/com/cronutils/model/definition/CronConstraint.java
- src/main/java/com/cronutils/model/definition/CronDefinition.java
- src/main/java/com/cronutils/model/field/CronField.java
- src/main/java/com/cronutils/model/field/constraint/FieldConstraints.java
- src/main/java/com/cronutils/model/field/definition/FieldDefinition.java
- src/main/java/com/cronutils/model/field/expression/FieldExpression.java
- src/main/java/com/cronutils/model/field/value/FieldValue.java
It's currently not possible to use com.cronutils.model.Cron as a member type in domain objects when using serialization-heavy frameworks like Apache Wicket.
This commit adds the java.io.Serializable interface to all direct  and indirect children of com.cronutils.model.Cron. I intentionally did not add an explicit serialVersionUID field to these classes since nobody (including me) remembers all the binary compatibility rules  (see https://wiki.eclipse.org/Evolving_Java-based_APIs_2) so maintaining this value is best left to the compiler. 
Maintenance-wise , I would probably add a disclaimer to the documentation stating that binary compatibility between versions is best-effort and breakage may occur (=so using Java serialization for long-term storage of these classes may be a bad idea).  
I …
> com.cronutils.model.Cron and all members should be serializable

- README.md
- src/main/java/com/cronutils/cli/CronUtilsCLI.java
- The help should be shown if -h option is alone
- validation action -> validate (verb)
- Fixed the documentation
- super() in constructor to avoid complains from quality tools for empty
method
- action no more required (so we can use the -h option alone)
> Small changes in CLI

- src/main/java/com/cronutils/model/time/ExecutionTime.java
- src/test/java/com/cronutils/model/time/ExecutionTimeQuartzIntegrationTest.java
Proposal to fix #192.
Although all test cases are passed the fix should be revised, since I did not yet understand the necessity of ExecutionTime#dateValuesInExpectedRanges. However the naive approach to solely compute nextExecution(date.minusSeconds(1)) and if present compare with date didn't work (i.e. causes some tests to fail).
> Fix for ExecutionTime#isMatch for lower bound date matching cron expression requirements (issue #192)

- src/androidTest/java/com/cronutils/model/time/ExecutionTimeQuartzIntegrationTest.java
- src/main/java/com/cronutils/model/time/generator/OnDayOfWeekValueGenerator.java
- src/test/java/com/cronutils/model/time/ExecutionTimeQuartzIntegrationTest.java
Previous change of the test case was wrong. my fault. sorry for that. it was me who confused DoM and DoW fields for whatever reason. unfortunately the original test succeeded by accident if the fields were interchanged.
Now L in the DoW field is effectively handled as 7 or SAT as in Quartz.
> effectively fixed #142

- src/test/java/com/cronutils/model/field/FieldParserTest.java
To pass the test, the created field now effectively needs to declare hash support. Previously hash was
handled although support of it may not have been declared.
@jmrozanec sorry that this fix of the test case got lost on the provided pull request
> Fixed issue on #194, i.e. fixed test case. 

- src/main/java/com/cronutils/model/definition/CronDefinitionBuilder.java
- src/test/java/com/cronutils/parser/CronParserCron4JIntegrationTest.java
Added supportsL() to the cron4j definition.
Added test case with cron4j cron expression using 'L'
> Fix issue #204 - cron4j definition should support L for day of month

- src/main/java/com/cronutils/model/definition/CronDefinition.java
- src/main/java/com/cronutils/model/definition/CronDefinitionBuilder.java
- src/main/java/com/cronutils/model/time/ExecutionTime.java
- src/test/java/com/cronutils/model/definition/CronDefinitionTest.java
- src/test/java/com/cronutils/model/time/ExecutionTimeCron4jIntegrationTest.java
Adds a matchDayOfWeekAndDayOfMonth option to the CronDefinitionBuilder. Defaults to false.
The cron4j definition sets it to true to match the cron4j specification.
ExecutionTime only generates dates that match both the day of week and day of month if matchDayOfWeekAndDayOfMonth of the CronDefinition is set to true.
> Fix #203 - add option to match both day of week and day of month

- src/test/java/com/cronutils/parser/CronParserCron4JIntegrationTest.java
The actual parse call was removed in 03c190a0f3cc767e537e4e01ee107835f1e5c0ce
> Restore test for #204 that was removed by 03c190a

- src/main/java/com/cronutils/model/time/ExecutionTime.java
- src/test/java/com/cronutils/model/time/generator/ExecutionTimeUnixIntegrationTest.java
The offset was not taken into account when creating the ZonedDateTime instances, leading to an infinite generation of the same next execution time in some cases.
For now the next execution time will output execution times falling within the DST overlaps.
Ex. "every x minutes" will actually output next execution times every x minutes, not skipping the overlap hour like some other cron implementations.
For cron patterns such as "15 1 * * *" (run at 1:15 AM every day), this will execute twice on that day since 1:15 AM actually does occur twice in the local time.
I think this behavior can be discussed in #213.
> Fix Issue #112

- src/main/java/com/cronutils/model/time/generator/BetweenDayOfWeekValueGenerator.java
- src/test/java/com/cronutils/Issue215Test.java
- handle the monday day of week used to generate the valid day of week (numeric) values
- replace usage of Java 8 time classes in the test with the backport
> Fix #215 by accounting for the shift in day of week by the cron definition

- src/test/java/com/cronutils/Issue228Test.java
Issue #228 has more examples of failures but these test probably cover what is needed.
> adding test representing failure of nextExecution() on Issue #228

- src/main/java/com/cronutils/model/definition/CronDefinitionBuilder.java
- src/main/java/com/cronutils/model/time/ExecutionTime.java
- src/main/java/com/cronutils/parser/CronParser.java
- src/test/java/com/cronutils/model/definition/CronDefinitionTest.java
Should resolve #221 by allowing the user to use cron-utils 6.0.3 with Java 7, which does not have a joda-time dependency.
> Replace usage of Java 8 stream classes with Java 7 compliant code.

- src/test/java/com/cronutils/Issue228Test.java
Use a custom cron definition in Issue228Test that meets the issue expectations.
> #228 - Replace UNIX cron definition in test with modified definition

- src/main/java/com/cronutils/model/time/generator/EveryFieldValueGenerator.java
* Removes only ZonedDateTime.now()
* Log statement forced early processing of logged objects
Fixes issue #256
> Remove log statement in EveryFieldValueGenerator

- src/main/java/com/cronutils/model/field/CronField.java
- src/main/java/com/cronutils/model/field/definition/FieldDefinition.java
- src/main/java/com/cronutils/model/field/expression/Always.java
- src/main/java/com/cronutils/model/field/expression/QuestionMark.java
- src/main/java/com/cronutils/model/time/ExecutionTime.java
- src/main/java/com/cronutils/parser/CronParser.java
- src/main/java/com/cronutils/parser/CronParserField.java
- src/test/java/com/cronutils/mapper/CronMapperIntegrationTest.java
- src/test/java/com/cronutils/model/CronTest.java
- src/test/java/com/cronutils/model/definition/CronDefinitionBuilderTest.java
- src/test/java/com/cronutils/model/field/constraints/FieldConstraintsTest.java
- src/test/java/com/cronutils/model/field/expression/visitor/ValidationFieldExpressionVisitorTest.java
- src/test/java/com/cronutils/model/time/ExecutionTimeQuartzWithDayOfYearExtensionIntegrationTest.java
- src/test/java/com/cronutils/model/time/generator/MockFieldValueGenerator.java
- src/test/java/com/cronutils/parser/CronParserTest.java
- src/test/java/com/cronutils/utils/descriptor/CronDescriptorTest.java
* Replace use of Guava Sets with constructors and native methods
* Replace use of Guava Maps with constructors
* Replace use of Guava Range with native methods
* Replace use of Guava MoreObjects in toString() with string concatenation
From the discussions in Issue #259
> Remove Guava from Maven Dependencies

- pom.xml
- src/test/java/com/cronutils/model/time/ExecutionTimeQuartzWithDayOfYearExtensionIntegrationTest.java
Fix some tests not defined correctly, fails once every 14th day as discovered in #271 
Related to #249
> Fix ExecutionTimeQuartzWithDayOfYearExtensionIntegrationTest

- src/main/java/com/cronutils/model/time/ExecutionTime.java
- src/main/java/com/cronutils/utils/Predicates.java
- src/test/java/com/cronutils/OpenIssuesTest.java
Fix potential null pointer exception for issue #274
Extract logic for next/previous year, month, DoM, hour, minute and second for methods `ExecutionTime.potentialNextClosestMatch()` and `ExecutionTime.potentialPreviousClosestMatch()`
Replace nested collection creation `new ArrayList<>(new HashSet<>(list)).sort()` with Stream API `list.stream().distinct().sort().collect(Collectors.tolist())`
Add locale for OpenIssuesTest, failing for some regional default locales.
> Restructure large methods in ExecutionTime

- src/test/java/com/cronutils/model/time/ExecutionTimeCustomDefinitionIntegrationTest.java
Creating a custom CronDefinition with only 3 required fields is legal to instantiate, but the parser considers an expression with 4 fields as an error:
> java.lang.IllegalArgumentException: Cron expression contains 4 parts but we expect one of [6, 7]
> Custom CronDefinition with 3 required fields behaves oddly.

- src/test/java/com/cronutils/Issue143Test.java
Based on the Quartz documentation, I think the asserted date is incorrect.
The cron pattern matches the 31st day of the month, any day of the week, any month of the year, and any year. October 31 fits that criteria.
http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html
> Fix expected date in testCase3 for #289

- src/main/java/com/cronutils/descriptor/CronDescriptor.java
If someone wants to utilize the I8N methodology in CronDescriptor in a piecemeal way, it is currently impossible to access those methods. To do so requires creating a local modified copy of all classes under src/main/java/com/cronutils/descriptor
> Make descriptor piecemeal methods public

- src/main/java/com/cronutils/descriptor/CronDescriptor.java
- src/test/java/com/cronutils/utils/descriptor/CronDescriptorTest.java
Our team realized that from an i8n perspective, providing public access to internationalized text in the resource bundle is potentially helpful if for some reason you need to "build-your-own" text description.
This is thus a minor tweak to the edit in https://github.com/jmrozanec/cron-utils/pull/298.
For example, our use case is that we are using cron-utils + a time duration to describe period(s) of time, so we use describeDayOfWeek(), describeMonth(), describeDayOfMonth(), and then build our own custom version of describeHHmmss() - for this function it would be helpful to have access to the current CronDescriptor ResourceBundle to ensure i8n is standardized.
> Follow-up to making minor methods public. Provide access to resource bundle.

- src/main/java/com/cronutils/model/field/expression/On.java
- src/test/java/com/cronutils/model/field/expression/OnTest.java
Previously, the expression `L-3` would be serialized as `L-3L`
> Fix string representation of On field with L

- src/main/java/com/cronutils/model/time/ExecutionTime.java
- src/test/java/com/cronutils/model/time/generator/ExecutionTimeUnixIntegrationTest.java
It is a partial fix for #310 (validation coming up in next PR)
This fixes a potential infinite loop for cron that will never be true. I think it's safer to stop somewhere then potentially running infinitely on some case in the future.
> Stop iteration in while loop 100 years from now

- src/test/java/com/cronutils/model/time/ExecutionTimeCron4jIntegrationTest.java
- src/test/java/com/cronutils/model/time/ExecutionTimeQuartzIntegrationTest.java
- src/test/java/com/cronutils/model/time/ExecutionTimeQuartzWithDayOfYearExtensionIntegrationTest.java
Fixing unit tests to expect SingleExecutionTime.class instead of ExecutionTime.class.
> Fixing unit tests

- src/main/java/com/cronutils/parser/CronParser.java
- src/test/java/com/cronutils/model/time/ExecutionTimeCustomDefinitionIntegrationTest.java
to support multiple, not only one optional field in cron definition.
> #291 - modify cron parser building possible expressions logic 

- src/main/java/com/cronutils/model/time/SingleExecutionTime.java
- src/test/java/com/cronutils/Issue319Test.java
Fixes #319 
I think we can follow this up by simplifying and consolidating the logic for the day, month, and year fields as well. And we can likely do a similar thing for next time computation. This would allow us to replace some of the fragile logic in `TimeNode` with something a bit more straightforward.
> Correctly handle DST when getting previous value

- src/main/java/com/cronutils/descriptor/CronDescriptor.java
- src/test/java/com/cronutils/utils/descriptor/CronDescriptorQuartzIntegrationTest.java
Fixes the UnknownFormatConversionException for the year portion.
There is a bad description when describing every X months (ex. */2 on the month gives `every February months` instead of `every 2 months`), but I think that should be another issue.
> #300 - Fix UnknownFormatConversionException

- src/main/java/com/cronutils/model/definition/CronDefinitionBuilder.java
- src/test/java/com/cronutils/model/definition/Issue343Test.java
Add test to cover the examples listed in the spring javadoc.
Fixes #343
> Remove quartz specific cron validation from the spring cron definition.

- pom.xml
- src/main/java/com/cronutils/validation/Cron.java
- src/main/java/com/cronutils/validation/CronValidator.java
- src/test/java/com/cronutils/validation/CronValidatorTest.java
If you want to use it in your project, you'll have to provide the
javax.validation validation-api library on the classpath.
Only supports the definitions provided by CronDefinitionBuilder.instanceDefinitionFor(CronType).
> Add optional jsr 303 validator.

- src/main/java/com/cronutils/model/definition/CronDefinitionBuilder.java
- src/test/java/com/cronutils/validator/CronValidatorQuartzIntegrationTest.java
Quartz cron expressions should allow overflowing ranges.
Fixes #396
> Quartz cron expressions should allow overflowing ranges

- src/main/java/com/cronutils/model/time/SingleExecutionTime.java
- src/test/java/com/cronutils/Issue394Test.java
Fixes #394 
All possible days of the month was being returned.
> When generating day candidates, take the intersection of days generated from DoW and DoM instead of union

- src/test/java/com/cronutils/Issue404Test.java
The tests show that a cron for all days of the week to start at midnight does not work for november 3 using the zoneid America/Sao_Paulo
> Added test for issue #404

- src/main/java/com/cronutils/parser/CronParser.java
- src/main/java/com/cronutils/parser/FieldParser.java
- src/test/java/com/cronutils/parser/CronParserTest.java
This fixes issue #412 
The issue was on line 184 of the cronparser. In this case, the hash was the only value, so when the split method gets called, it returns an empty list. 
Please note the build was failing prior to this pull request due to other issues and have I not fixed it for this bug fix.
> Check for case where hash is the last value of cron expression #412

- src/test/java/com/cronutils/Issue423Test.java
A test demonstrating a disconnect between expectation/reality for a slightly odd expression one of my clients is using -- `0 0 0-07,17-0 ? * SAT`.
It parses just fine, and generates a descriptor `every hour between 0 and 7 and every hour between 17 and 0 at Saturday day`, but the `ExecutionTime` skips the `17-0` interval and jumps straight to the next Saturday.
> Issue 423: Strange results for a strange expression

- pom.xml
> slf4j-simple is only needed for testing

- pom.xml
Use the recommended Lombok scope: https://projectlombok.org/setup/maven to avoid including it in the library clients' classpath/distribution. Closes #437 .
> Change Lombok dependency scope

- src/main/java/com/cronutils/descriptor/DescriptionStrategyFactory.java
- src/main/java/com/cronutils/model/field/expression/Every.java
- src/test/java/Issue421Test.java
With this PR I'm aiming to solve issue #421 .
I checked the test and it seems that the library is behaving as expected, following cron style: "every(6)" should not be intended as "every 6 months", but "on every 6th month", meaning on January and July.
The library also allows to compute "every 6h month" starting from a date, if you use the "every(on(_date_), 6)" method.
For this reason, I added some javadoc on the "Every" class, to explain its usage, and added additional tests in the test class created for issue #421. 
I did my best to make the explanation clear but I really appreciate feedbacks.
> Fix every description and fix #421

- src/main/java/com/cronutils/descriptor/refactor/SecondsDescriptor.java
- src/main/java/com/cronutils/model/field/expression/Always.java
- src/main/java/com/cronutils/model/field/expression/And.java
- src/main/java/com/cronutils/model/field/expression/Between.java
- src/main/java/com/cronutils/model/field/expression/Every.java
- src/main/java/com/cronutils/model/field/expression/FieldExpression.java
- src/main/java/com/cronutils/model/field/expression/On.java
- src/main/java/com/cronutils/model/field/expression/QuestionMark.java
- src/main/java/com/cronutils/model/field/expression/visitor/FieldExpressionVisitor.java
- src/main/java/com/cronutils/model/field/expression/visitor/FieldExpressionVisitorAdaptor.java
- src/main/java/com/cronutils/model/field/expression/visitor/ValidationFieldExpressionVisitor.java
- src/main/java/com/cronutils/model/field/expression/visitor/ValueMappingFieldExpressionVisitor.java
- src/test/java/com/cronutils/model/field/expression/FieldExpressionTest.java
- src/test/java/com/cronutils/model/field/expression/visitor/ValidationFieldExpressionVisitorTest.java
- src/test/java/com/cronutils/model/field/expression/visitor/ValueMappingFieldExpressionVisitorTest.java
This is the more usual way the visitor pattern is implemented. It avoids
requiring a bunch of explicit instanceof tests for each sub-type.
Also, add a FieldExpressionVisitorAdaptor utility class.
> Rework FieldExpressionVisitor so that subtypes invoke the correct method.

- pom.xml
This allows the project to be used with JPMS, though not `jlink`. In the future, the project should likely be fully modularized to allow usage with `jlink`.
> Add an Automatic-Module-Name

- src/main/java/com/cronutils/descriptor/TimeDescriptionStrategy.java
- src/test/java/com/cronutils/utils/descriptor/CronDescriptorQuartzIntegrationTest.java
A hacky solution for #477. 
**Why hacky**: I am not particularly happy with the solution as it introduces even more `instanceof` special case handling in `TimeDescriptionStrategy.java`. It seems needed though because the code assumes generating descriptions is independent for each field. It's not and `TimeDescriptionStrategy.describe` is currently the only place where this lack of independence is taken into account.
**Bugs**: I think this discovered two bugs in the other, non-related tests.
> Describe "always ..." for HHMMSS

- src/main/java/com/cronutils/mapper/CronMapper.java
- src/main/java/com/cronutils/parser/FieldParser.java
- src/test/java/com/cronutils/mapper/CronMapperIntegrationTest.java
It fixes how the mapper handle the day of the week, leaving the interval untouched, but mapping the start day if present.
Also fixes the int mapping when parsing. In unix "7/3" should be parsed as "0/3"
Fixes #495
> Fix mapping of interval for the day of week

- src/main/java/com/cronutils/mapper/WeekDay.java
- src/test/java/com/cronutils/model/definition/CronDefinitionBuilderTest.java
It fixes the DoW to be map Sunday correctly to 1 instead of 8.
Have also included the unit test for the issue.
Fixes #508
> Fix exception thrown when DoW set as Sunday using QUARTZ definition #508

- src/main/java/com/cronutils/model/field/constraint/FieldConstraints.java
- src/main/java/com/cronutils/model/field/definition/FieldDefinition.java
- src/test/java/com/cronutils/model/definition/CronDefinitionTest.java
Necessary to get proper behavior for equals and hashcode in `CronDefinition`.
I also corrected the test class, the original tests were misleading because they used the very same instance of `FieldDefinition`s.
See #507 and #516
> Equals and hashcode for FieldConstraints and FieldDefinition

- pom.xml
Given the API is provided, I think it was the original intent.
From what I can see, it is only useful when using Hibernate Validator
and, in this case, users should push their EL implementation.
> Make jakarta.el implementation provided

- pom.xml
- pom.xml.jdk16
Testing performed:
- locally using Maven 3.8.6 and OpenJDK 11 ran a few commands like: `mvn test`, `mvn install`, `mvn package`, `mvn deploy` and all worked (except the actual upload to Sonatype for the last one)
- Ran the Github action test which uses OpenJDK 16 in my fork on Github
> Upgrade maven plugins
